image: homeassistant/raspberrypi-homeassistant

test:
  before_script:
    - touch key.pem home-assistant_v2.db
    - mv .secrets.yaml secrets.yaml

  script:
    - hass -c . --script check_config --info all
