image: homeassistant/raspberrypi-homeassistant

test:
  before_script:
    - touch key.pem
    - mv .secrets.yaml secrets.yaml
    - mv .data data

  script:
    - hass -c . --script check_config --info all
