# ips
router_ip: 127.0.0.1
lifx_ip: 127.0.0.1
google_wifi_ip: 127.0.0.1
android_tv_ip: 127.0.0.1

camera_server_url: 127.0.0.1
camera_status_url: http://127.0.0.1:12345/status.json

driveway_camera_image_url: http://127.0.0.1:12345/axis-cgi/jpg/image.cgi?cameraId=0123456789
driveway_camera_video_url: http://127.0.0.1:12345/axis-cgi/mjpg/video.cgi?cameraId=0123456789

backyard_camera_url: 127.0.0.1
backyard_camera_sensors_url: https://127.0.0.1:12345/sensors.json
backyard_camera_image_url: http://127.0.0.01:12345/photo.jpg

windy_url: https://embed.windy.com/
darksky_url: https://maps.darksky.net

# bluetooth
living_room_sensor_mac: A1:B2:C3:D4:E6:F7
basement_sensor_mac: A1:B2:C3:D4:E6:F7

# http
base_url: example.com
ssl_certificate: key.pem
ssl_key: key.pem

# credentials
camera_username: abcdefghijklmnopqrstuvwxyz0123456789
camera_password: abcdefghijklmnopqrstuvwxyz0123456789
darksky_api_key: abcdefghijklmnopqrstuvwxyz0123456789
github_access_token: abcdefghijklmnopqrstuvwxyz0123456789
xfinity_email: abcdefghijklmnopqrstuvwxyz0123456789
xfinity_password: abcdefghijklmnopqrstuvwxyz0123456789
amazon_username: abcdefghijklmnopqrstuvwxyz0123456789
amazon_password: abcdefghijklmnopqrstuvwxyz0123456789
