language: python

python:
  - "3.7"

before_install:
  - mkdir /config
  - touch key.pem home-assistant.db
  - mv .secrets.yaml secrets.yaml
  - mv .data data
  - sudo apt-get install -y g++ make libudev-dev libyaml-dev

install:
  - pip3 install homeassistant

script:
  - hass -c . --script check_config --info all
