- id: front_door_open
  alias: Front Door Open
  trigger:
  - entity_id: binary_sensor.front_door_status
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Front Door open !
    service: notify.pushbullet
  - data:
      message: door has been open for 5 minutes
      title: Front Door open !
    service: notify.living_room_tv
- id: back_door_open
  alias: Back Door Open
  trigger:
  - entity_id: binary_sensor.back_door_status
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Back Door open !
    service: notify.pushbullet
  - data:
      message: door has been open for 5 minutes
      title: Back Door open !
    service: notify.living_room_tv
- id: slider_open
  alias: Slider Open
  trigger:
  - entity_id: binary_sensor.slider_status
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Slider open !
    service: notify.pushbullet
  - data:
      message: door has been open for 5 minutes
      title: Slider open !
    service: notify.living_room_tv
- id: driveway_motion
  alias: Driveway Motion
  trigger:
  - entity_id: binary_sensor.driveway_camera_motion
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: motion detected in driveway
      title: Motion Detected !
    service: notify.pushbullet
  - data:
      data:
        duration: 5
        file:
          auth: basic
          password: !secret camera_password
          url: !secret driveway_camera_image_url
          username: !secret camera_username
        interrupt: 1
      message: motion detected in driveway
      title: Motion Detected !
    service: notify.living_room_tv
- id: good_morning
  alias: Good Morning
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: switch.coffee
    service: switch.turn_on
  - delay: 'minutes: 5'
  - data:
      entity_id: switch.coffee
    service: switch.turn_off
- id: good_night
  alias: Good Night
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.master_bedroom
    service: light.turn_off
