- id: front_door_open
  alias: Front Door Open
  trigger:
  - entity_id: binary_sensor.front_door_status
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Front Door open !
    service: notify.pushbullet
- id: back_door_open
  alias: Back Door Open
  trigger:
  - entity_id: binary_sensor.back_door_status
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Back Door open!
    service: notify.pushbullet
- id: slider_open
  alias: Slider Open
  trigger:
  - entity_id: binary_sensor.slider_status
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Slider open !
    service: notify.pushbullet
