- id: good_morning
  alias: Good Morning
  trigger:
  - at: 07:45:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: switch.coffee
    service: switch.turn_on
  - delay: 00:05:00
  - data:
      entity_id: switch.coffee
    service: switch.turn_off
- id: good_night
  alias: Good Night
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.master_bedroom
    service: light.turn_off
- id: front_door_open
  alias: Front Door Open
  trigger:
  - entity_id: binary_sensor.front_door_status
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Front Door open !
    service: notify.mobile_app_abi_moto_g_6
- id: back_door_open
  alias: Back Door Open
  trigger:
  - entity_id: binary_sensor.back_door
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Back Door open !
    service: notify.mobile_app_abi_moto_g_6
- id: slider_open
  alias: Slider Open
  trigger:
  - entity_id: binary_sensor.slider_status
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Slider open !
    service: notify.mobile_app_abi_moto_g_6
- id: left_garage_door_open
  alias: Left Garage Door Open
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_left_garage_door
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Left Garage Door open !
    service: notify.mobile_app_abi_moto_g_6
- id: right_garage_door_open
  alias: Right Garage Door Open
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_right_garage_door
    for: 00:05:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: door has been open for 5 minutes
      title: Right Garage Door open !
    service: notify.mobile_app_abi_moto_g_6
- id: driveway_motion
  alias: Driveway motion
  description: ''
  trigger:
  - entity_id: binary_sensor.driveway_motion
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: motion detected in driveway
      title: Motion Detected !
    service: notify.mobile_app_moto_g_6
- id: driveway_motion_tv
  alias: Driveway Motion TV
  trigger:
  - entity_id: binary_sensor.driveway_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: media_player.bravia_tv
    state: 'on'
  action:
  - data:
      data:
        duration: 5
        file:
          auth: basic
          password: !secret camera_password
          url: !secret driveway_camera_image_url
          username: !secret camera_username
      message: motion detected in driveway
      title: Motion Detected !
    service: notify.living_room_tv
- id: backyard_motion
  alias: Backyard motion
  description: ''
  trigger:
  - entity_id: binary_sensor.backyard_motion
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: motion detected in backyard
      title: Motion Detected !
    service: notify.mobile_app_moto_g_6
- id: backyard_motion_tv
  alias: Backyard Motion TV
  description: ''
  trigger:
  - entity_id: binary_sensor.backyard_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: media_player.bravia_tv
    state: 'on'
  action:
  - data:
      data:
        duration: 5
        file:
          auth: basic
          password: !secret camera_password
          url: !secret backyard_camera_image_url
          username: !secret camera_username
      message: motion detected in backyard
      title: Motion Detected !
    service: notify.living_room_tv
- id: alarm_on
  alias: Turn on the alarm when I leave home
  description: ''
  trigger:
  - entity_id: person.abi
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data: {}
    entity_id: alarm_control_panel.alexa_guard
    service: alarm_control_panel.alarm_arm_away
- id: alarm_off
  alias: Turn off the alarm when I enter home
  description: ''
  trigger:
  - entity_id: person.abi
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data: {}
    entity_id: alarm_control_panel.alexa_guard
    service: alarm_control_panel.alarm_disarm
- id: trash_out_notification
  alias: Notify me to put trash can out
  description: ''
  trigger:
  - at: '18:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - wed
  action:
  - data:
      message: Time to put the trash can out
      title: Trash
    service: notify.mobile_app_moto_g_6
- id: mail_box_notification
  alias: Mail box notification
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_mailbox_motion
    from: Clear
    platform: state
    to: Detected
  condition: []
  action:
  - data:
      title: Mailbox
      message: Mail has arrived
    service: notify.mobile_app_moto_g_6
- id: save_lovelace_config
  alias: Save Lovelace Config
  description: ''
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - data: {}
    service: shell_command.save_lovelace
