- id: front_door_open
  alias: Front Door Open
  trigger:
  - platform: state
    entity_id:
    - sensor.front_door_status
    from: closed
    to: open
  action:
  - service: notify.pushbullet
    data:
      message: Front door open
- id: back_door_open
  alias: Back Door Open
  trigger:
  - platform: state
    entity_id:
    - sensor.back_door_status
    from: closed
    to: open
  action:
  - service: notify.pushbullet
    data:
      message: Back door open
- id: slider_open
  alias: Slider Open
  trigger:
  - entity_id:
    - sensor.slider_status
    from: closed
    platform: state
    to: open
  action:
  - data:
      message: Slider open
    service: notify.pushbullet
