homeassistant:
  name: Ada
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 50
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
config:
frontend:
  themes: !include_dir_merge_named themes
updater:
discovery:
conversation:
history:
logbook:
recorder:
  purge_keep_days: 1
sun:
map:
cast:
tts:
  - platform: google
cloud:
zwave:
  usb_path: !secret zwave_usb_path

group: !include groups.yaml
automation: !include automations.yaml
zone: !include configuration/zone.yaml
light: !include_dir_merge_list configuration/light
switch: !include_dir_merge_list configuration/switch
# camera: !include_dir_merge_list configuration/camera
sensor: !include_dir_merge_list configuration/sensor
notify: !include_dir_merge_list configuration/notify
weather: !include_dir_merge_list configuration/weather
# media_player: !include_dir_merge_list configuration/media_player
device_tracker: !include_dir_merge_list configuration/device_tracker
# binary_sensor: !include_dir_merge_list configuration/binary_sensor
