homeassistant:
  name: Ada
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 80
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
duckdns:
  domain: !secret subdomain
  access_token: !secret duckdns_access_token
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_networks:
    - ::1
    - 127.0.0.1
    - 192.168.86.0/24
    - fd00::/8
config:
frontend:
  themes: !include_dir_merge_named themes
updater:
discovery:
  ignore:
    - apple_tv
    - roku
conversation:
history:
  include:
    domains:
      - light
      - switch
      - sensor
      - device_tracker
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.worldclock_sensor
logbook:
logger:
  default: warning
recorder:
  purge_keep_days: 1
sun:
map:
cast:
tts:
  - platform: google
zwave:
  usb_path: !secret zwave_usb_path
ifttt:
  key: !secret ifttt_api_key

zone: !include zone.yaml
group: !include group.yaml
automation: !include automation.yaml
switch: !include_dir_merge_list configuration/switch
camera: !include_dir_merge_list configuration/camera
sensor: !include_dir_merge_list configuration/sensor
notify: !include_dir_merge_list configuration/notify
weather: !include_dir_merge_list configuration/weather
media_player: !include_dir_merge_list configuration/media_player
device_tracker: !include_dir_merge_list configuration/device_tracker
