# https://www.home-assistant.io/getting-started/configuration/
homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config

# https://www.home-assistant.io/integrations/default_config/
default_config:

automation: !include automations.yaml

lifx: !include components/lifx.yaml
http: !include components/http.yaml
zwave: !include components/zwave.yaml
logger: !include components/logger.yaml
recorder: !include components/recorder.yaml
frontend: !include components/frontend.yaml
panel_iframe: !include components/panel_iframe.yaml
android_ip_webcam: !include components/android_ip_webcam.yaml

tts: !include_dir_merge_list components/tts
notify: !include_dir_merge_list components/notify
sensor: !include_dir_merge_list components/sensor
camera: !include_dir_merge_list components/camera
weather: !include_dir_merge_list components/weather
panel_custom: !include_dir_merge_list components/panel_custom
media_player: !include_dir_merge_list components/media_player
binary_sensor: !include_dir_merge_list components/binary_sensor
