# https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Ada
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 95
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

# https://home-assistant.io/components/duckdns/
duckdns:
  domain: !secret subdomain
  access_token: !secret duckdns_access_token

# https://home-assistant.io/components/http/
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_networks:
    - ::1
    - 127.0.0.1
    - 192.168.86.0/24
    - fd00::/8

# https://home-assistant.io/components/config/
config:

# https://home-assistant.io/components/frontend/
frontend:
  themes: !include_dir_merge_named themes

# https://home-assistant.io/components/updater/
updater:

# https://home-assistant.io/components/system_health/
system_health:

# https://home-assistant.io/components/discovery/
discovery:
  ignore:
    - apple_tv
    - roku

# https://home-assistant.io/components/history/
history:
  include:
    domains:
      - light
      - switch
      - sensor
      - device_tracker
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.worldclock_sensor

# https://home-assistant.io/components/logbook/
logbook:
  include:
    domains:
      - light
      - switch
      - sensor
      - device_tracker
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.worldclock_sensor

# https://home-assistant.io/components/logger/
logger:
  default: warning

# https://home-assistant.io/components/recorder/
recorder:
  purge_keep_days: 3
  exclude:
    domains:
      - automation
      - updater
      - zone
      - zwave
    entities:
      - sun.sun

# https://home-assistant.io/components/sun/
sun:

# https://home-assistant.io/components/map/
map:

# https://home-assistant.io/docs/z-wave/
zwave:
  usb_path: !secret zwave_usb_path
  device_config_glob:
    "binary_sensor.*":
      ignored: true
    "sensor.*_alarm_type":
      ignored: true
    "sensor.*_sourcenodeid":
      ignored: true

# https://home-assistant.io/components/ifttt/
ifttt:
  key: !secret ifttt_api_key

# https://home-assistant.io/components/mqtt/
mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

# https://home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  server_id: 1774
  monitored_conditions:
    - download
    - upload

# https://home-assistant.io/components/person/
person:

# https://home-assistant.io/components/zone/
zone: !include zone.yaml

# https://home-assistant.io/components/automation/
automation: !include automation.yaml

# https://home-assistant.io/components/switch/
switch: !include_dir_merge_list configuration/switch

# https://home-assistant.io/components/camera/
camera: !include_dir_merge_list configuration/camera

# https://home-assistant.io/components/sensor/
sensor: !include_dir_merge_list configuration/sensor

# https://home-assistant.io/components/notify/
notify: !include_dir_merge_list configuration/notify

# https://home-assistant.io/components/weather/
weather: !include_dir_merge_list configuration/weather

# https://home-assistant.io/components/media_player/
media_player: !include_dir_merge_list configuration/media_player

# https://home-assistant.io/components/device_tracker/
device_tracker: !include_dir_merge_list configuration/device_tracker
