homeassistant:
  name: Ada
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 50
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
config:
frontend:
updater:
discovery:
conversation:
history:
logbook:
sun:
map:
cast:
tts:
  - platform: google

# zwave:
#   usb_path: /dev/cu.usbmodem1411

group: !include_dir_merge_named group
#scripts: !include_dir_merge_named scripts
#automation: !include_dir_merge_named automation
zone: !include configuration/zone.yaml
light: !include_dir_merge_list configuration/light
switch: !include_dir_merge_list configuration/switch
sensor: !include_dir_merge_list configuration/sensor
notify: !include_dir_merge_list configuration/notify
media_player: !include_dir_merge_list configuration/media_player
device_tracker: !include_dir_merge_list configuration/device_tracker
