# https://home-assistant.io/docs/components/basic/
homeassistant:
  name: Ada
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 95
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.86.0/24
        - fd00::/8

sun:
map:
person:
config:
logbook:
history:
updater:
system_health:

automation: !include automations.yaml

http: !include components/http.yaml
zone: !include components/zone.yaml
zwave: !include components/zwave.yaml
logger: !include components/logger.yaml
duckdns: !include components/duckdns.yaml
frontend: !include components/frontend.yaml
recorder: !include components/recorder.yaml
discovery: !include components/discovery.yaml
panel_iframe: !include components/panel_iframe.yaml
telegram_bot: !include components/telegram_bot.yaml
google_assistant: !include components/google_assistant.yaml
custom_updater: !include custom_components/custom_updater.yaml

notify: !include_dir_merge_list components/notify
sensor: !include_dir_merge_list components/sensor
camera: !include_dir_merge_list components/camera
weather: !include_dir_merge_list components/weather
media_player: !include_dir_merge_list components/media_player
binary_sensor: !include_dir_merge_list components/binary_sensor
device_tracker: !include_dir_merge_list components/device_tracker
