title: Home
views:
  - title: Ada
    id: ada
    icon: mdi:castle
    cards:
    - type: weather-forecast
      entity: weather.yahoo_weather
    - type: weather-forecast
      entity: weather.dark_sky
    - type: vertical-stack
      cards:
      - type: glance
        title: Doors and Windows
        entities:
          - sensor.front_door_status
          - sensor.back_door_status
          - sensor.slider_status
      - type: glance
        title: Lights and Switches
        entities:
          - light.living_room_light
          - switch.bedroom_light
    - type: vertical-stack
      cards:
      - type: map
        title: Home
        aspect_ratio: 100%
        default_zoom: 10
        entities:
          - device_tracker.abi
          - zone.home
      - type: entity-filter
        entities:
          - device_tracker.abi
        state_filter:
          - home
        card:
          type: glance
        show_empty: false
    - type: conditional
      conditions:
      - entity: media_player.living_room_tv
        state: "playing"
      card:
        title: what's playing
        type: entities
        entities:
          - media_player.living_room_tv
    - type: conditional
      conditions:
      - entity: media_player.living_room_speaker
        state: "playing"
      card:
        title: what's playing
        type: entities
        entities:
          - media_player.living_room_speaker

  - title: Living room
    id: living_room
    icon: mdi:sofa
    cards:
    - type: entities
      entities:
        - light.living_room_light
    - type: media-control
      entity: media_player.living_room_tv
    - type: media-control
      entity: media_player.living_room_speaker

  - title: Bedroom
    id: bedroom
    icon: mdi:hotel
    cards:
    - type: entities
      entities:
        - switch.bedroom_light
