title: Home
views:
  - title: Ada
    id: ada
    theme: night
    tab_icon: mdi:mdi:home-assistant
    cards:
    - title: Weather
      type: glance
      entities:
        - sun.sun
        - sensor.weather_symbol
        - sensor.weather_temperature
    - title: Doors and Windows
      type: glance
      entities:
        - binary_sensor.fdstatus
    - title: Lights and Switches
      type: glance
      entities:
        - light.living_room_light
        - switch.bedroom_light
    - type: entity-filter
      entities:
        - device_tracker.abi
      state_filter:
        - home
      card:
        title: who's home
        type: glance
    - type: conditional
      conditions:
      - entity: media_player.living_room_tv
        state: "playing"
      card:
        title: what's playing
        type: entities
        entities:
          - media_player.living_room_tv
    - type: conditional
      conditions:
      - entity: media_player.living_room_speaker
        state: "playing"
      card:
        title: what's playing
        type: entities
        entities:
          - media_player.living_room_speaker

  - title: Living room
    id: living_room
    icon: mdi:sofa
    cards:
    - type: entities
      entities:
        - light.living_room_light
    - type: media-control
      entity: media_player.living_room_tv
    - type: media-control
      entity: media_player.living_room_speaker

  - title: Bedroom
    id: bedroom
    icon: mdi:hotel
    cards:
    - type: entities
      entities:
        - switch.bedroom_light
