# https://www.home-assistant.io/integrations/binary_sensor.template
- platform: template
  sensors:

    front_door:
      friendly_name: "Front Door"
      device_class: door
      value_template: '{{ is_state("sensor.front_door_access_control", "22") }}'
    back_door:
      friendly_name: "Back Door"
      device_class: door
      value_template: '{{ is_state("sensor.back_door_access_control", "22") }}'
    slider:
      friendly_name: "Slider"
      device_class: door
      value_template: '{{ is_state("sensor.slider_access_control", "22") }}'

    driveway_motion:
      friendly_name: "Driveway Motion"
      device_class: motion
      value_template: '{{ is_state("sensor.camera_motion", "Driveway Camera") }}'
