- platform: template
  sensors:
    front_door_status:
      friendly_name: "Front Door"
      value_template: >-
        {% if is_state("sensor.front_door_access_control", "22") %}
        open
        {% else %}
        closed
        {%- endif %}
    back_door_status:
      friendly_name: "Back Door"
      value_template: >-
        {% if is_state("sensor.back_door_access_control", "22") %}
        open
        {% else %}
        closed
        {%- endif %}
    slider_status:
      friendly_name: "Slider"
      value_template: >-
        {% if is_state("sensor.slider_access_control", "22") %}
        open
        {% else %}
        closed
        {%- endif %}
