- platform: yr
  forecast: 24
  monitored_conditions:
    - temperature
    # - symbol
    # - precipitation
    # - windSpeed
    # - pressure
    # - windDirection
    - humidity
    - fog
    - cloudiness
    # - lowClouds
    # - mediumClouds
    # - highClouds
    # - dewpointTemperature
