# https://www.home-assistant.io/integrations/darksky/
- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - temperature
    - humidity
    - alerts
  scan_interval:
    minutes: 30
