# https://www.home-assistant.io/integrations/file#sensor
- platform: file
  name: Electricity Usage
  file_path: !secret electricity_usage
  value_template: '{{ value_json.usage }}'
  unit_of_measurement: kWh

- platform: file
  name: Water Usage
  file_path: !secret water_usage
  value_template: '{{ value_json.usage }}'
  unit_of_measurement: CCF

- platform: file
  name: Gas Usage
  file_path: !secret gas_usage
  value_template: '{{ value_json.usage }}'
  unit_of_measurement: Gallons
