- platform: mqtt
  state_topic: "homeassistant/sensor/android_abi_moto_g6_ariela_battery/state"
  name: "Moto G6 Battery"
  device_class: battery
  value_template: "{{ value_json.level }}"
  unit_of_measurement: "%"
  # json_attributes:
  #   - voltage
  #   - temperature
  #   - status
  #   - power
  #   - health
  #   - technology

