# https://www.home-assistant.io/integrations/rest
- platform: rest
  name: Camera Cpu Use Percent
  resource: !secret camera_status_url
  username: !secret camera_username
  password: !secret camera_password
  authentication: basic
  value_template: '{{ value_json.cpuUsagePercentage }}'
  unit_of_measurement: '%'
  json_attributes:
    # - backgroundMode
    # - cpuUsagePercentage
    # - temperature
    - memoryFree
    - memoryUsed
    # - battery
    - uptime
    # - networkIn
    # - networkOut
    # - streamProfile
    # - powerSafeMode
    # - notifications
    # - recorded
    # - available
    # - liveConnections
    - motion
