- platform: template
  sensors:
    sunset:
      value_template: >
        {% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M") %}
        {{ timestamp.lstrip("0") }}
      unit_of_measurement: 'PM'
    sunrise:
      value_template: >
        {% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M") %}
        {{ timestamp.lstrip("0") }}
      unit_of_measurement: 'AM'
