- platform: template
  sensors:
    sunset:
      friendly_name: "Sunset"
      value_template: '{{ (as_timestamp(state_attr("sun.sun", "next_setting")) | timestamp_custom("%I:%M")).lstrip("0") }}'
      unit_of_measurement: 'PM'
      icon_template: mdi:weather-sunset-down
    sunrise:
      friendly_name: "Sunrise"
      value_template: '{{ (as_timestamp(state_attr("sun.sun", "next_rising")) | timestamp_custom("%I:%M")).lstrip("0") }}'
      unit_of_measurement: 'AM'
      icon_template: mdi:weather-sunset-up
