# https://www.home-assistant.io/integrations/systemmonitor
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: last_boot
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
