# https://www.home-assistant.io/components/sensor.template/
- platform: template
  sensors:

    front_door_battery:
      friendly_name: "Front Door Battery"
      device_class: battery
      value_template: '{{ state_attr("zwave.front_door", "battery_level") }}'
      unit_of_measurement: '%'
    back_door_battery:
      friendly_name: "Back Door Battery"
      device_class: battery
      value_template: '{{ state_attr("zwave.back_door", "battery_level") }}'
      unit_of_measurement: '%'
    slider_battery:
      friendly_name: "Slider Battery"
      device_class: battery
      value_template: '{{ state_attr("zwave.slider", "battery_level") }}'
      unit_of_measurement: '%'

    sunset:
      friendly_name: "Sunset"
      value_template: '{{ (as_timestamp(state_attr("sun.sun", "next_setting")) | timestamp_custom("%I:%M")).lstrip("0") }}'
      unit_of_measurement: 'PM'
      icon_template: mdi:weather-sunset-down
    sunrise:
      friendly_name: "Sunrise"
      value_template: '{{ (as_timestamp(state_attr("sun.sun", "next_rising")) | timestamp_custom("%I:%M")).lstrip("0") }}'
      unit_of_measurement: 'AM'
      icon_template: mdi:weather-sunset-up

    moon_phase:
      friendly_name: Moon
      value_template: '{{ states.sensor.moon.state }}'
      entity_picture_template: /local/moon_phases/{{ states.sensor.moon.state }}.jpg

    camera_memory_use_percent:
      friendly_name: Camera Memory Use Percent
      value_template: >-
        {% set memoryUsed = states.sensor.camera_cpu_use_percent.attributes["memoryUsed"] | replace("MB", "") | int %}
        {% set memoryFree = states.sensor.camera_cpu_use_percent.attributes["memoryFree"] | replace("MB", "") | int %}
        {{ (memoryUsed/(memoryFree + memoryUsed) * 100) | round() }}
      unit_of_measurement: '%'
      icon_template: mdi:memory
    camera_uptime:
      friendly_name: Camera Uptime
      value_template: >-
        {% set arr = states.sensor.camera_cpu_use_percent.attributes["uptime"].split(' ') %}
        {% if arr[-6] %}{% set d = arr[-6] | int %}{% else %}{% set d = 0 %}{% endif %}
        {% if arr[-4] %}{% set h = arr[-4] | int %}{% else %}{% set h = 0 %}{% endif %}
        {% if arr[-2] %}{% set m = arr[-2] | int %}{% else %}{% set m = 0 %}{% endif %}
        {{ (d + h/24 + m/1440) | round(2) }}
      unit_of_measurement: 'days'
      icon_template: mdi:timelapse
    camera_motion:
      friendly_name: Camera Motion
      value_template: '{{ states.sensor.camera_cpu_use_percent.attributes["motion"] }}'
