# https://www.home-assistant.io/components/camera.mjpeg/
- platform: mjpeg
  name: Driveway Camera
  mjpeg_url: !secret driveway_camera_video_url
  username: !secret camera_username
  password: !secret camera_password
  authentication: basic
