- platform: template
  sensors:
    fdstatus:
      friendly_name: "Front Door"
      device_class: door
      value_template: >-
        {% if is_state("sensor.front_door_access_control", "22") %}
        open
        {% else %}
        closed
        {%- endif %}
