name: Check
on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: SetUp
      run: |
        mkdir /config
        touch key.pem home-assistant.db
        mv .secrets.yaml secrets.yaml
        mv .data data

    - name: Version
      uses: "docker://homeassistant/home-assistant:stable"
      with:
        args: >
          python -m homeassistant --version

    - name: Check
      uses: "docker://homeassistant/home-assistant:stable"
      with:
        args: python -m homeassistant --config . --script check_config --info all
