name: Main workflow
on: [push]
jobs:
  check:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install homeassistant
        touch key.pem
        mv .secrets.yaml secrets.yaml
        hass -c . --script check_config --info all
