name: Check
on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: SetUp
      run: |
        touch key.pem home-assistant_v2.db
        mv .secrets.yaml secrets.yaml
        sed -i 's/\/config/${{ github.workspace }}/' configuration.yaml

    - name: Check
      uses: "docker://homeassistant/home-assistant:stable"
      with:
        args: python -m homeassistant --config . --script check_config --info all
